---

- name: Dump all variables
  connection: local
  local_action: template src=environment.j2 dest={{ inventory_dir }}/environment.log

- name: ensure common packages are present
  apt: name={{ item }} state=present update_cache=yes
  sudo_user: root
  with_items:
    - curl
    - manpages
    - vim
    - wget
